# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.3.0"
selene = "Kampfkarren/selene@0.25.0"
stylua = "johnnymorganz/stylua@0.17.1"
luau-lsp = "johnnymorganz/luau-lsp@1.18.1"
remodel = "UpliftGames/remodel@0.12.0-uplift.release.12"
wally = "UpliftGames/wally@0.3.2"
lune = "filiptibell/lune@0.7.1"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
darklua = "seaofvoices/darklua@0.9.0"
wally-package-types = "JohnnyMorganz/wally-package-types@1.2.1"
