[package]
name = "love-barn/senshi"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.packages"

[dependencies]
t = "osyrisrblx/t@3.1.1"

Matter = "matter-ecs/matter@0.7.1"
Plasma = "matter-ecs/plasma@0.4.3"
Rewire = "sayhisam1/rewire@0.3.0"
MatterHooks = "matter-ecs/matter-hooks@0.2.0"

Net = "vorlias/net@3.0.6"
Sift = "csqrl/sift@0.0.8"
Loader = "sleitnick/loader@2.0.0"
Signal = "sleitnick/signal@2.0.1"

React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
VirtualizedList = "jsdotlua/virtualized-list@1.3.5"

[server-dependencies]
Lapis = "nezuo/lapis@0.2.9"
DataStoreServiceMock = "nezuo/data-store-service-mock@0.3.5"
Mock-Memory-Store-Service = "vorlias/mock-memory-store-service@0.2.0"
