local GRID_EDGE_LENGTH = 20000
local SWITCH_THRESHOLD = 100
local MAXIMUM_DISTANCE_FROM_ORIGIN = GRID_EDGE_LENGTH / 2.0 + SWITCH_THRESHOLD

return {
	GRID_EDGE_LENGTH = GRID_EDGE_LENGTH,
	SWITCH_THRESHOLD = SWITCH_THRESHOLD,
	MAXIMUM_DISTANCE_FROM_ORIGIN = MAXIMUM_DISTANCE_FROM_ORIGIN,
}
